spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: kafka:9094
    consumer:
      group-id: notification-group
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com # Замените на ваш email
    password: your_password # Замените на ваш пароль
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  eureka:
    client:
      serviceUrl:
        defaultZone: http://eureka:8761/eureka/
    instance:
      preferIpAddress: true
