spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/user_service
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  application:
    name: user-service
  cloud:
    config:
      uri: http://config:8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
