spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/*
    config:
      uri: http://config:8888
  eureka:
    client:
      serviceUrl:
        defaultZone: http://eureka:8761/eureka/
    instance:
      preferIpAddress: true